export const TOKEN_CONFIG = {
    name: "DevDots",
    symbol: "DDT",
    description: "DevDots Token",
    decimals: 9,
    initialSupply: 1000000,
    image: "https://image.url",
    externalUrl: "https://devdots.org",
    website: "https://devdots.org",
    twitter: "https://twitter.com/devdots",
    telegram: "https://t.me/devdots",
    discord: "https://discord.gg/devdots",
    github: "https://github.com/devdots",
    disableMintingAfterInit: false,
    sellerFeeBasisPoints: 0,
}